Django/Demo/monprojet/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    # Les route pour les livres
    path('', views.book_list, name='book_list'),
    path('<int:id>/', views.book_detail, name='book_detail'),
    path('add_book/', views.add_book, name='add_book'),
    path('update_book/<int:id>/', views.update_book, name='update_book'),
    path('delete_book/<int:id>/', views.delete_book, name='delete_book'),
    # Les route pour les codes
    path('codes/', views.code_list, name='code_list'),
    path('add_code/', views.add_code, name='add_code'),
    path('code_delete/<int:id>', views.code_delete, name='code_delete'),
    path('code_update/<int:id>', views.code_update, name='code_update'),
]

Django/Demo/monprojet/monprojet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('books/', include('books.urls')),
    path('publishers/', include('publishers.urls')),
    path('teste/', include('teste.urls')),
]

Django/Demo/monprojet/publishers/urls.py
from django.urls import path
from . import views

app_name = 'publishers'

urlpatterns = [
    path('', views.publisher_list, name='publisher_list'),
    path('<int:id>/', views.publisher_detail, name='publisher_detail'),
    path('delete_publisher/<int:id>/', views.delete_publisher, name='delete_publisher'),
    path('update_publisher/<int:id>/', views.update_publisher, name='update_publisher'),
    path('add_publisher/', views.add_publisher, name='add_publisher'),
]

Django/Demo/monprojet/books/models.py
from django.utils import timezone
from django.db import models
from authors.models import Author
from publishers.models import Publisher

class ISBN(models.Model):
    code = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(null=True, blank=True)
    modified_at = models.DateTimeField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:  # Si l'objet est en train d'être créé
            self.created_at = timezone.now()
            self.modified_at = None
        else:
            self.modified_at = timezone.now()
        super(ISBN, self).save(*args, **kwargs)

    def __str__(self):
        return self.code

class Book(models.Model):
    title = models.CharField(max_length=200)
    publication_date = models.DateField()
    summary = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)  # ForeignKey (plusieurs livres peuvent avoir un même auteur)
    isbn = models.OneToOneField(ISBN, on_delete=models.CASCADE)  # OneToOneField (chaque livre a un ISBN unique)
    publishers = models.ManyToManyField(Publisher)  # ManyToManyField (un livre peut avoir plusieurs éditeurs)

    created_at = models.DateTimeField(null=True, blank=True)
    modified_at = models.DateTimeField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:  # Si l'objet est en train d'être créé
            self.created_at = timezone.now()
            self.modified_at = None
        else:
            self.modified_at = timezone.now()
        super(Book, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

Django/Demo/monprojet/publishers/models.py
from django.utils import timezone
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)

    created_at = models.DateTimeField(null=True, blank=True)
    modified_at = models.DateTimeField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:  # Si l'objet est en train d'être créé
            self.created_at = timezone.now()
            self.modified_at = None
        else:
            self.modified_at = timezone.now()
        super(Publisher, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

Django/Demo/monprojet/publishers/forms.py
from django import forms
from .models import Publisher

class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ['name', 'address']

Django/Demo/monprojet/publishers/views.py
from django.shortcuts import redirect, render, get_object_or_404

from .forms import PublisherForm
from .models import Publisher

def publisher_list(request):
    publishers = Publisher.objects.all()
    return render(request, 'publishers/publisher_list.html', {'publishers': publishers})

def publisher_detail(request, id):
    publisher = get_object_or_404(Publisher, id=id)
    return render(request, 'publishers/publisher_detail.html', {'publisher': publisher})

def add_publisher(request):
    if request.method == 'POST':
        form = PublisherForm(request.POST)
        if form.is_valid():
            form.save()  # Enregistre le livre en base de données
          # Redirige vers la liste des publishers après ajout
            return redirect('publishers:publisher_list')
    else:
        form = PublisherForm()
    return render(request, 'publishers/publisher_form.html', {'form': form})

def delete_publisher(request, id):
    publisher = get_object_or_404(Publisher, id=id)
    publisher.delete()
    return redirect('publishers:publisher_list')

def update_publisher(request, id):
    publisher = get_object_or_404(Publisher, id=id)
    if request.method == 'POST':
        # Liaison avec l'instance existante
        form = PublisherForm(request.POST, instance=publisher)  
        if form.is_valid():
            form.save()  # Met à jour l'edition existante
            return redirect('publishers:publisher_list')
    else:
         # Pré-remplissage pour modification
        form = PublisherForm(instance=publisher) 
    return render(request, 'publishers/publisher_form.html', {'form': form})

Django/Demo/monprojet/publishers/templates/publishers/publisher_detail.html
{% extends "base.html" %}

{% block title %}Détail de l'Éditeur{% endblock %}

{% block content %}
    <h2>Détails de l'Éditeur</h2>

    <p><strong>Nom :</strong> {{ publisher.name }}</p>

    <h3>Livres publiés par cet éditeur :</h3>
    <ul>
        {% for book in publisher.book_set.all %}
            <li>{{ book.title }} ({{ book.publication_date }})</li>
        {% endfor %}
    </ul>

    <a href="{% url 'publishers:publisher_list' %}">Retour à la liste des éditeurs</a>
{% endblock %}

Django/Demo/monprojet/publishers/templates/publishers/publisher_form.html
{% extends "base.html" %}
{% block content %}
<h2>Ajouter une edition</h2>
<form method="POST">
    {% csrf_token %}
    <!-- Affiche tous les champs sous forme de paragraphes -->
    {{ form.as_p }}  
    <button type="submit">Ajouter l'edition</button>
</form>
{% endblock content %}

Django/Demo/monprojet/publishers/templates/publishers/publisher_list.html
{% extends "base.html" %}
{% block title %}Liste des Éditeurs{% endblock %}
{% block content %}
    <h2>Liste des Éditeurs</h2>
    <ul>
        {% for publisher in publishers %}
            <li>
                <a href="{% url 'publishers:publisher_detail' publisher.id %}">{{ publisher.name }}</a>
                <!-- Supprimer un auteur -->
                <a style="color : red" href="{% url 'publishers:delete_publisher' publisher.id %}">Supprimer</a>
                <!-- Mettre à jour un auteur -->
                <a style="color : green" href="{% url 'publishers:update_publisher' publisher.id %}">Modifier</a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'publishers:add_publisher' %}">Ajouter une edition</a>
{% endblock %}