Django/Demo/monprojet/authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    # Liste des auteurs
    path('', views.author_list, name='author_list'),  
      # Détails d'un auteur
    path('<int:id>/', views.author_detail, name='author_detail'), 
      # Ajouter un auteur
    path('add_author/', views.add_author, name='add_author'), 
      # Supprimer un auteur
    path('delete_author/<int:id>/', views.delete_author, name='delete_author'), 
    # Mettre à jour un auteur
    path('update_author/<int:id>/', views.update_author, name='update_author'),  
]

Django/Demo/monprojet/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    # Les route pour les livres
    path('', views.book_list, name='book_list'),
    path('<int:id>/', views.book_detail, name='book_detail'),
    path('add_book/', views.add_book, name='add_book'),
    path('update_book/<int:id>/', views.update_book, name='update_book'),
    path('delete_book/<int:id>/', views.delete_book, name='delete_book'),
    # Les route pour les codes
    path('codes/', views.code_list, name='code_list'),
    path('add_code/', views.add_code, name='add_code'),
    path('code_delete/<int:id>', views.code_delete, name='code_delete'),
    path('code_update/<int:id>', views.code_update, name='code_update'),
]

Django/Demo/monprojet/monprojet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('books/', include('books.urls')),
    path('publishers/', include('publishers.urls')),
    path('teste/', include('teste.urls')),
]

Django/Demo/monprojet/publishers/urls.py
from django.urls import path
from . import views

app_name = 'publishers'

urlpatterns = [
    path('', views.publisher_list, name='publisher_list'),
    path('<int:id>/', views.publisher_detail, name='publisher_detail'),
    path('delete_publisher/<int:id>/', views.delete_publisher, name='delete_publisher'),
    path('update_publisher/<int:id>/', views.update_publisher, name='update_publisher'),
    path('add_publisher/', views.add_publisher, name='add_publisher'),
]

Django/Demo/monprojet/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mon Site Django{% endblock %}</title>
</head>
<body>
    <header>
        <h1>Bienvenue sur mon site de gestion de livres</h1>
        <nav>
            <ul>
                <li><a href="{% url 'authors:author_list' %}">Auteurs</a></li>
                <li><a href="{% url 'books:book_list' %}">Livres</a></li>
                <li><a href="{% url 'books:code_list' %}">Codes</a></li>
                <li><a href="{% url 'publishers:publisher_list' %}">Éditeurs</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        <!-- Le contenu spécifique sera injecté ici -->
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Mon Projet Django</p>
    </footer>
</body>
</html>

Django/Demo/monprojet/templates/header.html
{% extends "base.html" %}

{% block title %}Liste des Éditeurs{% endblock %}
{% block content %}
    <h2>Liste des Éditeurs</h2>
 <ul>
    {% for publisher in publishers %}
        <li>
        <a href="{% url 'publishers:publisher_detail' publisher.id %}">
        {{ publisher.name }}
        </a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}