Django/Demo/monprojet/authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    # Liste des auteurs
    path('', views.author_list, name='author_list'),  
      # Détails d'un auteur
    path('<int:id>/', views.author_detail, name='author_detail'), 
      # Ajouter un auteur
    path('add_author/', views.add_author, name='add_author'), 
      # Supprimer un auteur
    path('delete_author/<int:id>/', views.delete_author, name='delete_author'), 
    # Mettre à jour un auteur
    path('update_author/<int:id>/', views.update_author, name='update_author'),  
]

Django/Demo/monprojet/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    # Les route pour les livres
    path('', views.book_list, name='book_list'),
    path('<int:id>/', views.book_detail, name='book_detail'),
    path('add_book/', views.add_book, name='add_book'),
    path('update_book/<int:id>/', views.update_book, name='update_book'),
    path('delete_book/<int:id>/', views.delete_book, name='delete_book'),
    # Les route pour les codes
    path('codes/', views.code_list, name='code_list'),
    path('add_code/', views.add_code, name='add_code'),
    path('code_delete/<int:id>', views.code_delete, name='code_delete'),
    path('code_update/<int:id>', views.code_update, name='code_update'),
]

Django/Demo/monprojet/monprojet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('books/', include('books.urls')),
    path('publishers/', include('publishers.urls')),
    path('teste/', include('teste.urls')),
]

Django/Demo/monprojet/books/models.py
from django.utils import timezone
from django.db import models
from authors.models import Author
from publishers.models import Publisher

class ISBN(models.Model):
    code = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(null=True, blank=True)
    modified_at = models.DateTimeField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:  # Si l'objet est en train d'être créé
            self.created_at = timezone.now()
            self.modified_at = None
        else:
            self.modified_at = timezone.now()
        super(ISBN, self).save(*args, **kwargs)

    def __str__(self):
        return self.code

class Book(models.Model):
    title = models.CharField(max_length=200)
    publication_date = models.DateField()
    summary = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)  # ForeignKey (plusieurs livres peuvent avoir un même auteur)
    isbn = models.OneToOneField(ISBN, on_delete=models.CASCADE)  # OneToOneField (chaque livre a un ISBN unique)
    publishers = models.ManyToManyField(Publisher)  # ManyToManyField (un livre peut avoir plusieurs éditeurs)

    created_at = models.DateTimeField(null=True, blank=True)
    modified_at = models.DateTimeField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:  # Si l'objet est en train d'être créé
            self.created_at = timezone.now()
            self.modified_at = None
        else:
            self.modified_at = timezone.now()
        super(Book, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

Django/Demo/monprojet/books/forms.py
from django import forms
from .models import ISBN, Book

class ISBNForm(forms.ModelForm):
    class Meta:
        model = ISBN
        fields = ['code']
        widgets = {
            'code': forms.TextInput(attrs={'placeholder': 'Code ISBN'}),
        }
        
class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'publication_date', 'summary', 'author', 'isbn', 'publishers']
       
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Titre du livre'}),
            'publication_date': forms.DateInput(attrs={'type': 'date'}),
            'summary': forms.Textarea(attrs={'placeholder': 'Résumé du livre'}),
        }

Django/Demo/monprojet/books/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404

from .forms import BookForm, ISBNForm
from .models import ISBN, Book

def book_list(request):
    books = Book.objects.all()
    return render(request, 'books/book_list.html', {'books': books})

def book_detail(request, id):
    book = get_object_or_404(Book, id=id)
    return render(request, 'books/book_detail.html', {'book': book})

def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()  # Enregistre le livre en base de données
          # Redirige vers la liste des livres après ajout
            return redirect('books:book_list')
    else:
        form = BookForm()
    return render(request, 'books/book_form.html', {'form': form})

def delete_book(request, id):
    book = get_object_or_404(Book, id=id)
    book.delete()
    return redirect('books:book_list')

def update_book(request, id):
    book = get_object_or_404(Book, id=id)
    if request.method == 'POST':
        # Liaison avec l'instance existante
        form = BookForm(request.POST, instance=book)  
        if form.is_valid():
            form.save()  # Met à jour l'auteur existant
            return redirect('books:book_list')
    else:
         # Pré-remplissage pour modification
        form = BookForm(instance=book) 
    return render(request, 'books/book_form.html', {'form': form})






def code_list(request):
    codes = ISBN.objects.all()
    return render(request, 'books/code_list.html', {'codes': codes})

def add_code(request):
    if request.method == 'POST':
        form = ISBNForm(request.POST)
        if form.is_valid():
            form.save()  # Enregistre le code ISBN
         # Redirige vers la liste des codes
            return redirect('books:code_list') 
    else:
        form = ISBNForm()
    return render(request, 'books/code_form.html', {'form': form})

def code_delete(request, id):
    code = get_object_or_404(ISBN, id=id)
    code.delete()
    return redirect('books:code_list')

def code_update(request, id):
    code = get_object_or_404(ISBN, id=id)
    if request.method == 'POST':
        # Liaison avec l'instance existante
        form = ISBNForm(request.POST, instance=code)  
        if form.is_valid():
            form.save()  # Met à jour l'auteur existant
            return redirect('books:code_list')
    else:
         # Pré-remplissage pour modification
        form = ISBNForm(instance=code) 
    return render(request, 'books/code_form.html', {'form': form})

Django/Demo/monprojet/books/templates/books/book_detail.html
{% extends "base.html" %}

{% block title %}Détail du Livre{% endblock %}

{% block content %}
    <h2>Détails du Livre</h2>

    <p><strong>Titre :</strong> {{ book.title }}</p>
    <p><strong>Date de publication :</strong> {{ book.publication_date }}</p>
    <p><strong>Résumé :</strong> {{ book.summary }}</p>
    <p><strong>Auteur :</strong> <a href="{% url 'authors:author_detail' book.author.id %}">{{ book.author.name }}</a></p>
    <p><strong>Éditeurs :</strong></p>
    <ul>
        {% for publisher in book.publishers.all %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'books:book_list' %}">Retour à la liste des livres</a>
{% endblock %}

Django/Demo/monprojet/books/templates/books/book_form.html
{% extends "base.html" %}
{% block content %}
<h2>Ajouter un Livre</h2>
<form method="POST">
    {% csrf_token %}
    <!-- Affiche tous les champs du formulaire sous forme de paragraphes -->
    {{ form.as_p }}  
    <button type="submit">Ajouter</button>
</form>
{% endblock %}

Django/Demo/monprojet/books/templates/books/book_list.html
{% extends "base.html" %}

{% block title %}Liste des Livres{% endblock %}

{% block content %}
    <h2>Liste des Livres</h2>
    <ul>
        {% for book in books %}
            <li>
            <a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a>
            {% comment %} Supprimer {% endcomment %}
            <a style="color : red" href="{% url 'books:delete_book' book.id %}">Supprimer</a>
            <!-- Mettre à jour un auteur -->
            <a style="color : green" href="{% url 'books:update_book' book.id %}">Modifier</a>
           </li>
        {% endfor %}
    </ul>
    <a href="{% url 'books:add_book' %}">Ajouter un livre</a>
{% endblock %}

Django/Demo/monprojet/books/templates/books/code_form.html
{% extends "base.html" %}
{% block content %}

<h2>Ajouter un Code ISBN</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}  <!-- Affiche le champ du code ISBN -->
    <button type="submit">Ajouter</button>
</form>

{% endblock  %}

Django/Demo/monprojet/books/templates/books/code_list.html
{% extends "base.html" %}
{% block title %}Liste des Code{% endblock %}
{% block content %}
    <h2>Liste des Codes</h2>
    <ul>
        {% for code in codes %}
        <li>
                <span >{{ code.code }}</span>
            <a style="color : red" href="{% url 'books:code_delete' code.id %}">Supprimer</a>
            <!-- Mettre à jour un auteur -->
            <a style="color : green" href="{% url 'books:code_update' code.id %}">Modifier</a>
        </li>
        {% endfor %}
    </ul>
        <!-- Lien pour ajouter un auteur avec des données factices -->
        <a href="{% url 'books:add_code' %}">Ajouter un code</a>
{% endblock %}